# Generated by Django 6.0 on 2025-12-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
